name: Snake Animation

on:
  schedule:
    - cron: "0 */24 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Snake
        uses: miccy/snake-evolution@v1.3.0
        with:
          github_user_name: intensed-dev
          outputs: dist/snake.svg
          theme: github-dark

      - name: Push Snake SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update snake animation"
          add: "dist/snake.svg"
